name: 'Create reminder'

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  reminder:
    permissions:
      issues: write  # for agrc/create-reminder-action to set reminders on issues
      pull-requests: write  # for agrc/create-reminder-action to set reminders on PRs
    runs-on: ubuntu-latest

    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@f42017c218a09767e4ad6833cf9f66cbe00bfb7d # v1.1.14
