on:
  pull_request:
    branches:
      - master
      - 'release/**'

name: Check modified markdown files
permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
        config-file: .github/workflows/markdown-link/config.json
  markdown-lint:
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
        # Full git history is needed to get a proper
        # list of changed files within `super-linter`
        fetch-depth: 0
    - name: Lint Markdown
      uses: super-linter/super-linter@56576d491db07c7236b445ab09991ca49d12b0c6 # v6.5.0
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        FILTER_REGEX_INCLUDE: .*\.md
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_EDITORCONFIG: false
